language:
  node_js
install:
  - npm install -g codecov
sudo: true
dist: trusty
node_js:
- 8.9.1
after_success:
- npm run semantic-release
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- yarn
script:
- yarn test -- --coverage
- codecov